### PR TITLE
Proposed changes to README

### PR DESCRIPTION
**Pull request by sankarshanmukhopadhyay**
Adding a little bit of explanation for the project - based on some clarifications received from Srikanth L

### CODE REVIEW

**Comment by qurbat** [comment]
Thank you @sankarshanmukhopadhyay. I will take a look at this soon and update you.

**Comment by qurbat** [comment]
@sankarshanmukhopadhyay @srikanthlogic I've made a few small changes to the text. Please take a look and let me know if it looks OK.

**Review by sankarshanmukhopadhyay — COMMENTED** [review]
Looks good!

**Comment by srikanthlogic** [comment]
LGTM too

**Pull request merged**
